/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.ArrayList;
import modelDominio.Receita;
import view.tablemodel.ReceitaTableModel;

/**
 *
 * @author Aila
 */
public class FormCategoriaExpandida extends javax.swing.JDialog {

    private ReceitaTableModel receitamodel;
    int tipoRecebido = 0;
    /**
     * Creates new form FormCategoriaExpandida
     * @param tipo
     */
    public FormCategoriaExpandida(int tipo) {
        initComponents();
        this.tipoRecebido = tipo;
        atualizaTabela();
    }
    
    private void atualizaTabela() {
        ArrayList<Receita> listaReceita = ChefShopAdministrador.ccont.receitaLista(tipoRecebido);
        receitamodel = new ReceitaTableModel(listaReceita);
        jTTabelaReceitas.setModel(receitamodel);
        
        if (tipoRecebido == 1) {
            setTitle("Carnes");
        } else if (tipoRecebido == 2) {
            setTitle("Massas");
        } else if (tipoRecebido == 3) {
            setTitle("Saladas");
        } else if (tipoRecebido == 4) {
            setTitle("Sobremesas");
        } else if (tipoRecebido == 5) {
            setTitle("Sopas");
        } else if (tipoRecebido == 6) {
            setTitle("Lanches");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabelaReceitas = new javax.swing.JTable();
        jBAddReceita = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Categoria Expandida");

        jPanel1.setBackground(new java.awt.Color(251, 251, 248));

        jTTabelaReceitas.setAutoCreateRowSorter(true);
        jTTabelaReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome da Receita", "Ingredientes", "Modo de Preparo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTTabelaReceitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaReceitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTabelaReceitas);

        jBAddReceita.setBackground(new java.awt.Color(139, 187, 84));
        jBAddReceita.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jBAddReceita.setText("Adicionar receita nessa categoria");
        jBAddReceita.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), javax.swing.BorderFactory.createCompoundBorder()));
        jBAddReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddReceitaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(139, 187, 84));

        jButton1.setBackground(new java.awt.Color(139, 187, 84));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/voltar.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jBAddReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jBAddReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAddReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddReceitaActionPerformed
        // TODO add your handling code here:
        FormCadReceita frmcadrec = new FormCadReceita();
        frmcadrec.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBAddReceitaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormCategorias frmcat = new FormCategorias();
        frmcat.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTTabelaReceitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaReceitasMouseClicked
        // TODO add your handling code here:
        FormReceitaDetalhada frmrecdet = new FormReceitaDetalhada(receitamodel.getReceita(jTTabelaReceitas.getSelectedRow()));
        frmrecdet.setVisible(true);
    }//GEN-LAST:event_jTTabelaReceitasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddReceita;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTTabelaReceitas;
    // End of variables declaration//GEN-END:variables
}
